CREATE TABLE IF NOT EXISTS product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  category VARCHAR(255),
  name VARCHAR(255),
  price FLOAT(53),
  PRIMARY KEY (id)
);

INSERT INTO product (id, name, category, price)
VALUES (1, 'iPhone 12', 'Electronics', 999.99),
       (2, 'iPad 8', 'Electronics', 329.99),
       (3, 'Samsung Galaxy S20', 'Electronics', 899.99),
       (4, 'Amazon Echo Dot', 'Electronics', 49.99),
       (5, 'Sony PlayStation 5', 'Electronics', 499.99),
       (6, 'Nintendo Switch', 'Electronics', 299.99),
       (7, 'Nike Air Max 270', 'Clothing', 150.00),
       (8, 'Harry Potter and the Philosopher''s Stone', 'Books', 7.99),
       (9, 'Barbie Dreamhouse', 'Toys', 199.99),
       (10, 'Levi''s 501 Jeans', 'Clothing', 59.99),
       (11, 'The Great Gatsby', 'Books', 12.50),
       (12, 'LEGO Millennium Falcon', 'Toys', 799.99),
       (13, 'Adidas Ultraboost', 'Clothing', 180.00),
       (14, 'The Hobbit', 'Books', 9.99),
       (15, 'Fisher-Price Rock-a-Stack', 'Toys', 5.99);