-- Create a table named 'product' if it doesn't already exist
CREATE TABLE IF NOT EXISTS product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Unique identifier for each product
  category VARCHAR(255), -- Category of the product
  name VARCHAR(255), -- Name of the product
  price FLOAT(53), -- Price of the product
  PRIMARY KEY (id) -- Define 'id' as the primary key
);

-- Insert sample data into the 'product' table
INSERT INTO product (id, name, category, price) VALUES
  (1, 'iPhone 12', 'Electronics', 999.99), -- Sample product: iPhone 12
  (2, 'iPad 8', 'Electronics', 329.99), -- Sample product: iPad 8
  (3, 'Samsung Galaxy S20', 'Electronics', 899.99), -- Sample product: Samsung Galaxy S20
  (4, 'Amazon Echo Dot', 'Electronics', 49.99), -- Sample product: Amazon Echo Dot
  (5, 'Sony PlayStation 5', 'Electronics', 499.99), -- Sample product: Sony PlayStation 5
  (6, 'Nintendo Switch', 'Electronics', 299.99), -- Sample product: Nintendo Switch
  (7, 'Nike Air Max 270', 'Clothing', 150.00), -- Sample product: Nike Air Max 270
  (8, 'Harry Potter and the Philosopher''s Stone', 'Books', 7.99), -- Sample product: Harry Potter and the Philosopher's Stone
  (9, 'Barbie Dreamhouse', 'Toys', 199.99), -- Sample product: Barbie Dreamhouse
  (10, 'Levi''s 501 Jeans', 'Clothing', 59.99), -- Sample product: Levi's 501 Jeans
  (11, 'The Great Gatsby', 'Books', 12.50), -- Sample product: The Great Gatsby
  (12, 'LEGO Millennium Falcon', 'Toys', 799.99), -- Sample product: LEGO Millennium Falcon
  (13, 'Adidas Ultraboost', 'Clothing', 180.00), -- Sample product: Adidas Ultraboost
  (14, 'The Hobbit', 'Books', 9.99), -- Sample product: The Hobbit
  (15, 'Fisher-Price Rock-a-Stack', 'Toys', 5.99); -- Sample product: Fisher-Price Rock-a-Stack
